apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openldap
  namespace: openldap
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: openldap.systemtracker.no-ip.org
    http:
      paths:
      - backend:
          serviceName: openldap
          servicePort: 389
        path: /