apiVersion: batch/v1
kind: Job
metadata:
  name: copy
  namespace: openldap
spec:
  template:
    spec:
      serviceAccountName: openldap
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 10Mi
      - name: scripts
        configMap:
          defaultMode: 0755
          name: scripts
      containers:
      - name: configure
        image: alpine:3.15
        resources:
          requests:
            cpu: 20m
            memory: 200Mi
        volumeMounts:
          - name: scripts
            mountPath: /scripts/
          - name: cache-volume
            mountPath: /cache
        command: ["/bin/sh", "-c"]
        args:
          - apk add --update --no-cache --quiet curl coreutils; apk --quiet upgrade;
            cp /sripts/* /cache/;
            ./cache/configure.sh;
            sleep 2;
      restartPolicy: Never
  backoffLimit: 4