apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml
  #- ingress.yaml

patches:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: openldap
    namespace: openldap
    labelSelector: "app.kubernetes.io/name=openldap-stack-ha"
  patch: |-
    - op: replace #action 
      path: "/spec/template/spec/containers/0/ports/0" #resouirce we want to change
      value:
        name: ldap-port
        containerPort: 389
        protocol: TCP
    - op: replace #action 
      path: "/spec/template/spec/containers/0/ports/1" #resouirce we want to change
      value:
        name: ssl-ldap-port
        containerPort: 636
        protocol: TCP
