apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml
  #- ingress.yaml

patches:
  - path: patch.yaml
    target:
      version: v1
      kind: StatefulSet
      name: openldap
