apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml
  #- ingress.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: openldap
      namespace: openldap
    path: patch.yaml
