apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml
  #- ingress.yaml

patches:
- patch: |-
    - op: replace #action 
      path: "/spec/template/spec/containers/0/ports/0/containerPort" #resouirce we want to change
      value: 389 #value we want to use for patching 
    - op: replace #action 
      path: "/spec/template/spec/containers/0/ports/1/containerPort" #resouirce we want to change
      value: 636 #value we want to use for patching 
  target:
    kind: StatefulSet
    name: openldap
    namespace: openldap
