apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./core

patches:
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: openldap
      namespace: openldap
    spec:
      template:
        spec:
          containers:
            - name: openldap-stack-ha
              image: osixia/openldap:stable-arm64v8
              command: ['sh', '-c']
              args:
              - "cp /ldifs/* /container/service/slapd/assets/config/bootstrap/ldif/custom/ && echo copied;"