apiVersion: v1
kind: ServiceAccount
metadata:
  name: openldap
  namespace: openldap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openldap
  namespace: openldap
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - create 
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openldap
  namespace: openldap
subjects:
  - kind: ServiceAccount
    name: openldap
roleRef:
  kind: Role
  name: openldap
  apiGroup: rbac.authorization.k8s.io