apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: mysql-operator
      version: "2.0.9"
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
        namespace: keycloak
      interval: 5m
  values:
    image:
      registry: container-registry.oracle.com
      repository: mysql
      name: community-operator
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""
      pullSecrets:
        enabled: false
        secretName:

    envs:
        imagesPullPolicy: IfNotPresent
        imagesDefaultRegistry: 
        imagesDefaultRepository:
        k8sClusterDomain:

    # If you would like to debug the Helm output with `helm template`, you need
    # to turn disableLookups on as during `helm template` Helm won't contact the kube API
    # and all lookups will thus fail
    disableLookups: false