apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
  namespace: keycloak
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi