apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: keycloak
  labels:
    app: mysql
    version: "5.7"
spec:
  selector:
    matchLabels:
      app: mysql
      version: "5.7"
  serviceName: "mysql-service"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql
        version: "5.7"
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: mysql
        image: "mysql"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 3
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            cpu: 900m
            memory: 1200Mi
          requests:
            cpu: 300m
            memory: 400Mi
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: ROOT_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: "/var/lib/mysql"
          subPath: "mysql" 
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      storageClassName: "local-path"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi