apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spark-cert
  namespace: hadoop
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  dnsNames:
  - spark.systemtracker.no-ip.org
  secretName: spark.systemtracker.no-ip.org-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer