apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./stepcertificates
  - ./stepissuer
  - HelmRepository.yaml
  #- ClusterIssuer.yaml
  #- sealed-secret-ca.yaml
  #- sealed-secret.yaml
