apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #
  # Common services, as maintained by the Manifests WG
  #
  # istio 1.17 and gateway
  - ./common/istio-1-17/istio-crds/base/
  - ./common/istio-1-17/istio-namespace/base
  - ./common/istio-1-17/istio-install/base
  # Dex 
  - ./common/dex/overlays/istio
  # cert-manager is handled 
  #- HelmRelease.yaml
  #- HelmRepository.yaml
  #
  # OIDC Auth Service
  - ./common/oidc-authservice/base
  #
  # knative
  - ./common/knative/knative-serving/overlays/gateways
  - ./common/istio-1-17/cluster-local-gateway/base
  - ./common/knative/knative-eventing/base
  #
  # kf namesoace
  - ./common/kubeflow-namespace/base
  - ./common/kubeflow-roles/base
  - ./common/istio-1-17/kubeflow-istio-resources/base
  #
  #
  #
  # 3rd party contributed applications (e.g. Ray, Kserve), which are maintained externally and are not part of a Kubeflow WG
  # kf serving
  - ./contrib/kserve/kserve
  - ./contrib/kserve/models-web-app/overlays/kubeflow
  #
  #
  #  
  # Kubeflow's official components, as maintained by the respective Kubeflow WGs
  # kf pipelines
  - ./apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
  #- ./apps/pipeline/upstream/env/platform-agnostic-multi-user-pns
  #  
  # katib
  - ./apps/katib/upstream/installs/katib-with-kubeflow
  # central dashboard
  - ./apps/centraldashboard/upstream/overlays/kserve
  - ./apps/admission-webhook/upstream/overlays/cert-manager
  # notebook controller official kf components
  - ./apps/jupyter/notebook-controller/upstream/overlays/kubeflow
  # jupyter lab official kf components
  - ./apps/jupyter/jupyter-web-app/upstream/overlays/istio
  # profile controller and KFAM official kf components 
  - ./apps/profiles/upstream/overlays/kubeflow
  # volume web app and kf components 
  - ./apps/volumes-web-app/upstream/overlays/istio
  # tensorboard
  - ./apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
  # tensor controller
  - ./apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
  # training operator
  - ./apps/training-operator/upstream/overlays/kubeflow
  #
  #
  # Common services, as maintained by the Manifests WG
  # new ns for default user
  - ./common/user-namespace/base
