apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml
  - configMap.yaml
  - configMap-flows.yaml

  # ingress template for app
  #- ingress.yaml
