apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hadoop-yarn-nm
  namespace: hadoop
  labels:
    app.kubernetes.io/name: hadoop
    app.kubernetes.io/component: yarn-nm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hadoop
      app.kubernetes.io/component: yarn-nm
  minAvailable: 1