
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: hadoop-yarn-nm
  namespace: hadoop
  labels:
    app.kubernetes.io/name: hadoop
    app.kubernetes.io/component: yarn-nm
spec:
  ports:
  - port: 8088
    name: web
  - port: 8082
    name: web2
  - port: 8042
    name: api
  clusterIP: None
  selector:
    app.kubernetes.io/name: hadoop
    app.kubernetes.io/component: yarn-nm