# Service to access the yarn web ui
apiVersion: v1
kind: Service
metadata:
  name: hadoop-yarn-ui
  namespace: hadoop
  labels:
    app.kubernetes.io/name: hadoop
    app.kubernetes.io/component: yarn-ui
spec:
  ports:
  - port: 8088
    name: web
  selector:
    app.kubernetes.io/name: hadoop
    app.kubernetes.io/component: yarn-rm