apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: arc-runner
  namespace: arc-runner
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts