apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openldap
  namespace: openldap
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
spec:
  ingressClassName: nginx
  rules:
  - host: openldap.systemtracker.no-ip.org
    http:
      paths:
      - backend:
          service:
            name: openldap
            port:
              number: 389
        path: /
        pathType: ImplementationSpecific
