apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./arc-runner-scale-set-controller
  - ./arc-runner-scale-set
  - namespace.yaml
  #- sealed-secret.yaml
  #- Ingress.yaml
  #- RunnerDeployment.yaml its moved to apps.
  #- Certificate.yaml

