kind: ConfigMap
apiVersion: v1
metadata:
  name: scripts-init
  namespace: keycloak
data:
  init.sql: |
    \c keycloak;
    GRANT USAGE, CREATE ON SCHEMA public TO postgres;
    GRANT CREATE ON SCHEMA public TO keycloak;