apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- namespace.yaml
  - sealedsecrets.yaml
  - HelmRelease.yaml
  - HelmRepository.yaml
  #- Certificate.yaml
patches:
  # Hacky way to disable the default secret
  - target:
      kind: Secret
      name: pg-postgres
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: pg-postgres
        namespace: keycloak