apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg
  namespace: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pg
  namespace: keycloak
rules:
  - verbs:
      - list
      - get
    apiGroups:
      - "*"
    resources:
      - pods
      - pods/log
  - verbs:
      - "*"
    apiGroups:
      - "*"
    resources:
      - pods/exec
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pg
  namespace: keycloak
subjects:
  - kind: ServiceAccount
    name: openldap
roleRef:
  kind: Role
  name: openldap
  apiGroup: rbac.authorization.k8s.io