apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: kubeflow
spec:
  interval: 30m
  chart:
    spec:
      chart: spark-operator
      version: "1.2.7"
      sourceRef:
        kind: HelmRepository
        name: spark-operator
        namespace: kubeflow
      interval: 30m
  values:
    image:
      # -- Image repository
      repository: ghcr.io/kubeflow/spark-operator
      # -- Image pull policy
      pullPolicy: IfNotPresent
      # -- if set, override the image tag whose default is the chart appVersion.
      tag: ""
    nodeSelector:
      kubernetes.io/hostname: amd5
