apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: spark-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: spark-operator
      version: "1.3.1"
      sourceRef:
        kind: HelmRepository
        name: spark-operator
        namespace: kubeflow
      interval: 30m
  values:
    nodeSelector:
      kubernetes.io/hostname: amd5