apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: kubeflow
spec:
  interval: 30m
  chart:
    spec:
      chart: spark-operator
      version: "1.3.1"
      sourceRef:
        kind: HelmRepository
        name: spark-operator
        namespace: kubeflow
      interval: 30m
  values:
    image:
      # -- Image repository
      repository: docker.io/chainguard/spark-operator
      # -- Image pull policy
      pullPolicy: IfNotPresent
      # -- if set, override the image tag whose default is the chart appVersion.
      tag: "latest"
    nodeSelector:
      kubernetes.io/hostname: amd5
    batchScheduler:
      # -- Enable batch scheduler for spark jobs scheduling. If enabled, users can specify batch scheduler name in spark application
      enable: true