apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches: # customize the manifests during bootstrap
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          name: all
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: role
                          operator: In
                          values:
                            - flux
            tolerations:
              - effect: NoSchedule
                key: role
                operator: Equal
                value: flux    
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
