apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kps
  namespace: kps
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "46.6.0"
      sourceRef:
        kind: HelmRepository
        name: kps
        namespace: kps
      interval: 5m
  values:
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - grafana.systemtracker.no-ip.org