apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-issuer
  namespace: stepca
spec:
  interval: 30m
  chart:
    spec:
      chart: step-issuer
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: stepca
        namespace: stepca
      interval: 30m
  values:
    # Default values for step-issuer.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    replicaCount: 1

    image:
      repository: cr.step.sm/smallstep/step-issuer
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""

    kubeRBACproxy:
      image:
        repository: gcr.io/kubebuilder/kube-rbac-proxy
        pullPolicy: IfNotPresent
        tag: v0.8.0

    # List of secret keys used to pull images from private registries.
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    deployment:
      # Configure arguments to pass to the step issuer
      args:
        enableLeaderElection: true
        disableApprovalCheck: false
      terminationGracePeriodSeconds: 10

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 50Mi

    service:
      type: ClusterIP
      port: 8443
      targetPorts: https
      controlPlane: controller-manager
      scrape: true
      scrapePort: 8080

    serviceAccount:
      # Specifies whether a service account should be created
      create: false
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""

    # mandatory values to generate stepIssuer resource
    # please follow the https://github.com/smallstep/step-issuer#getting-started to setup step-ca and get step-issuer values
    stepIssuer:
      create: true
      caUrl: "https://step-certificates.stepca.svc.cluster.local"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3ekNDQVdtZ0F3SUJBZ0lRR3d4MXUwN29IazdtSFRDeFFWYmpRREFLQmdncWhrak9QUVFEQWpCQU1Sb3cKR0FZRFZRUUtFeEZUZEdWd0lFTmxjblJwWm1sallYUmxjekVpTUNBR0ExVUVBeE1aVTNSbGNDQkRaWEowYVdacApZMkYwWlhNZ1VtOXZkQ0JEUVRBZUZ3MHlOREExTWpVeE1EUXhNamhhRncwek5EQTFNak14TURReE1qaGFNRUF4CkdqQVlCZ05WQkFvVEVWTjBaWEFnUTJWeWRHbG1hV05oZEdWek1TSXdJQVlEVlFRREV4bFRkR1Z3SUVObGNuUnAKWm1sallYUmxjeUJTYjI5MElFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVNcll6cXB1bgpiTyszRE81L1VzanNac3lGczdIRW9FM2ttazV0bU1wdTM0UkdnYWcvcHA0d1BoRnRRbElrSG41NVAwc0VENGlWCnlUaS9QdmUyaHN1eVphTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOEMKQVFFd0hRWURWUjBPQkJZRUZKbVRFVjVGL2lLVFNxa0RFRUNBV3BiY2JJYy9NQW9HQ0NxR1NNNDlCQU1DQTBnQQpNRVVDSVFEWVBYSXptQ2duNjducDBST1V0ZCtFT1FHT3g4ZjVvd2luMWV1UmFyMG1kQUlnSGt5SEdoV2JmMlYwCjRyOEhCc0djM1NSbXZkMlVaRWVDYkYyYXN0ZC8zZjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      provisioner:
        name: "admin"
        kid: "2D-s3YPaqqz5IZkWYNDs94YEEQhlZJlNl23qFj3T15c"
        passwordRef:
          name: "step-certificates-provisioner-password"
          namespace: "stepca"
          key: "password"

    # mandatory values to generate stepClusterIssuer resource
    # please follow the https://github.com/smallstep/step-issuer#getting-started to setup step-ca and get step-issuer values
    stepClusterIssuer:
      create: false
      caUrl: "https://step-certificates.stepca.svc.cluster.local"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3ekNDQVdtZ0F3SUJBZ0lRR3d4MXUwN29IazdtSFRDeFFWYmpRREFLQmdncWhrak9QUVFEQWpCQU1Sb3cKR0FZRFZRUUtFeEZUZEdWd0lFTmxjblJwWm1sallYUmxjekVpTUNBR0ExVUVBeE1aVTNSbGNDQkRaWEowYVdacApZMkYwWlhNZ1VtOXZkQ0JEUVRBZUZ3MHlOREExTWpVeE1EUXhNamhhRncwek5EQTFNak14TURReE1qaGFNRUF4CkdqQVlCZ05WQkFvVEVWTjBaWEFnUTJWeWRHbG1hV05oZEdWek1TSXdJQVlEVlFRREV4bFRkR1Z3SUVObGNuUnAKWm1sallYUmxjeUJTYjI5MElFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVNcll6cXB1bgpiTyszRE81L1VzanNac3lGczdIRW9FM2ttazV0bU1wdTM0UkdnYWcvcHA0d1BoRnRRbElrSG41NVAwc0VENGlWCnlUaS9QdmUyaHN1eVphTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOEMKQVFFd0hRWURWUjBPQkJZRUZKbVRFVjVGL2lLVFNxa0RFRUNBV3BiY2JJYy9NQW9HQ0NxR1NNNDlCQU1DQTBnQQpNRVVDSVFEWVBYSXptQ2duNjducDBST1V0ZCtFT1FHT3g4ZjVvd2luMWV1UmFyMG1kQUlnSGt5SEdoV2JmMlYwCjRyOEhCc0djM1NSbXZkMlVaRWVDYkYyYXN0ZC8zZjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      provisioner:
        name: "admin"
        kid: "2D-s3YPaqqz5IZkWYNDs94YEEQhlZJlNl23qFj3T15c"
        passwordRef:
          name: "step-certificates-provisioner-password"
          namespace: "stepca"
          key: "password"

    # For the cert-manager approver
    certManager:
      serviceAccount:
        name: cert-manager
        namespace: cert-manager

    # Experimental support for the TLS-over-TLS tunnel in the step-ca client.
    # Do not enable this unless you know what to use.
    tunnel:
      enabled: false
      crt: "/opt/tunnel/tls.crt"
      key: "/opt/tunnel/tls.key"
      host: "" # host:port
      root: "/opt/tunnel/ca.crt"
      tlsCertsRef:
        secret:
          secretName: ""

    # Configure extra volumes and volume mounts as YAML expressions.
    volumes: false
    volumeMounts: false

    # nodeSelector contains the node labels for pod assignment.
    nodeSelector: {}

    # tolerations contains the toleration labels for pod assignment.
    tolerations: []

    # affinity contains the affinity settings for pod assignment.
    affinity: {}