apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  #ca:
  #  secretName: ssl-ingress-secret-ca
  acme: 
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "alok.hom@gmail.com"
    privateKeySecretRef: 
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx

    
