apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml
  #- Ingress.yaml
  #- RunnerDeployment.yaml its moved to apps.

