apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: arc-runner
spec:
  replicas: 1
  template:
    spec:
      repository: mumoshu/actions-runner-controller-ci