apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-runner
spec:
  encryptedData:
    github_token: AgCXyaYFJDNKNAS8b7Cg/Vbxa8vBPY1bu7B4BNlrlpdGOCXZvzaII8MaAjweU1xz2uvD5OnMYM/BsHLdPCCmvIYIGkrhRX0vauiGDnUXwZbMej9PYGYE/mD4SSOKHdar/n+sh1DY7246JUaaR0ZvriDp7aOq2EIjcG7lYNS+N+7Ts6ZY5DXa42l4AnxB0DHSvX4nZjXm4QOIPMi9RVNIFyXxytLZtc1Zc4KqqSI5z0G8wNRFm2tP95zVzxa0pEUONZLVLpguNFWjyDTGwRecZujovJbbKeeZvyLJvBRSL9Jc3MOOnwSGJVYyoINfxnzZ8QOj+9mQdAr+MT2oaE1dUcMRzPZ747QWJpQ4UjTjohdHMfFQfroN7w6LGE+gJl1hMvUmPjrzMibhn3W3OsksgaJ4CkutCvv0Pa/J6MOWh7cC+jBwfN5hMiXP14vj2stFrdjjbeqk6rjWGKtSu6XI9rl788eO4GuN5tduSMrwIgxsGc+aKEJ9Uyc1ELb9+sodivkkFa2mSP3QAoNeX0U4/4LinbNE9LZ2QztKgnN81ZGHiLWX3mK/kYknHi+Ui0wIsd3pX+h+8AXeJ32/z26xHPX8nCtBukGP6fYrQw257xBDB32sQNd7QlYfzq6G+8TDGumQ4ngMTo2U8Dmn7Blyx6A3wvmxV+ICHayDxJuPq8U31IjUH+AUDg1MOYfr1SZjZQ0q+EdXQaGIftS5//jiSvWOiARYkWooO9WlW1E5GdFxUzTUyr8Xy+1v     
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-runner