apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-runner
spec:
  encryptedData:
    github_token: AgBO28NDt1AgbgHwTVzdDaRwa9HPmO3GcyN5YHHE0nW3skQHK4KOdEInYEgn7NlyGBWt8q5xPTfbtDCtxWGoI/zQuIqU6F/kI0TPdYGexZ/MMXfVxBgrwi3bDdye27MCvfRcoCXdHSHqqGSf6rw+/xj1nGRSUbMV8JcgjVAFPO6eNDER5Vo+BwsLlIbcIBMZ0Gdn+yPsRxEMfrhnqQYv2y7za1K7Hf69jddIoVU2E1132rCCbnSAhuYnLXgSOWPz7LvGCivVMVqFBlAVdDga4VQXhnfCUYWfU15tWx2RoirsX7dw9UTyso2nNL0B+aytXbUdX05ACoq5t9aByaO7UiAtpVCbCalfqIEiXWzvIW6zlEJIVy8Fdf/5o2kCt5ZdbOYFEmm3OyKM/mOUBpYEXoaHsw1rZYeGv4f062bl76IZQeSgs+PKBcYhbuGA7jky5F6+GrW2BZ7KwOOUiPT2D4jrsEHNvNAhewWoImhAvcPd5w8Hgx9Qn5GaKpkh0IBe2CFMuP1UjC/RVBorjassxrn+OKO4bIZ0XwEnAhavhI+8hRqk8sogvEEiWpXA+KsvkxpmawtqDYkChvoWWYtY1veqk3rqJB5EDgyYAkR/wwmOpXNKumkdJhmLEXKjtSAn7qcxu4K1To0sbEyoLM2Ur054Wcs4O1myz866LYuD+6L01xgSUHNgLd/PL2Rs96/V4yDhUwC1LH8jAzRNuFwVwPtCTLFkeAXJQzy9o6spTsiFAyAa7EvVCyxw     
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-runner