apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: arc-runner
spec:
  encryptedData:
    github_token: AgBeme/2xbKvr+jL6BBizBeobargdFQcEZ/loyWvPqvd5abXVjDq6HL9TmUzzRngszdTu/ALSPWDetINKVlZWOJKoBdplFJgE7zpMn1ejGc46W9UU+zuhIyUFwBk9Ars/1cN1qVz732zmexpKgo/KXqgu3o5VWChHHpVMZ/46IDTEzqRfR8wdronRQtzaw1EizDke6sNohf4WJ1dwyDVLOgCVLvWWuQEqiGgN0A2XjL4R+nCw1rpB4sq8ayS9ARsTsJK3hL0nmPNAb31MLiPTKysM6cpqTpF5xPYBEEP0CGd6GpGpoyTRNn9q0jiypdaRwhxEunft+VXVGbFLCc6hlcrJK748I//6MCdqZawcx5CtoZZLj+Nm7L6MewNOqa+8t3V5S4NjC11IWfergJ20+zItYxLRTIKEtawz6ZO1P7gj8lUSOiWK/C1RrKht7phrbrZDdAiL4rTLfib2pnSOurWlxwUHn71AsSkaaiMh2hIVZ9Se37KhWQTz9NwQq246vyK26hJY0ONMbSQJI6ahZ0SZrnBCdd7nDGVvdBRw9zvQX3HfG7pfu8i6tukOX6Qk6TNC1/aIdgF6BbaJNBuKWlffhy80n312byUBuap9w3GXwpdPm2eNRidoQHEZSG47fObCMliAgeDaJwN68zGdrh3uvNGj+dpHGrCOUOmam16a+4drzjJ89+iZkh+yy+DGG/5gzwth9d8cKaZwlG3robV6dK+HWyvUJDPrXDc/MvjM5aVk5zJaluZ     
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: arc-runner