apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - image: quay.io/keycloak/keycloak:latest
        args: ["start", "--optimized"]
        name: keycloak
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_HOSTNAME
          value: localhost
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL_HOST
          value: "pg-postgres"
        - name: KC_DB_URL_DATABASE
          value: "keycloak"
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_USERNAME
          valueFrom: { secretKeyRef: { name: pg-postgres, key: USERDB_USER } }
        - name: KC_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: pg-postgres, key: USERDB_PASSWORD } }
        - name: jgroups.dns.query
          value: keycloak
        ports:
        - name: jgroups
          containerPort: 7600
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /health/ready
            port: 8443
          initialDelaySeconds: 60
          periodSeconds: 1
      restartPolicy: Always