apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  ports:
  - port: 8080
    name: http
  - port: 8443
    name: https
  clusterIP: None
  selector:
    app.kubernetes.io/name: keycloak