apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  serviceName: "keycloak"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: quay.io/keycloak/keycloak:20.0
        args: ["start", "--cache-stack=kubernetes"]
        name: keycloak
        resources:
          requests:
            cpu: "800m"
            memory: "200Mi"
          limits:
            cpu: "900m"
            memory: "400Mi"
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_HOSTNAME
          value: localhost
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL_HOST
          value: "pg-postgres"
        - name: KC_DB_URL_DATABASE
          value: "keycloak"
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_USERNAME
          valueFrom: { secretKeyRef: { name: pg-postgres, key: USERDB_USER } }
        - name: KC_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: pg-postgres, key: USERDB_PASSWORD } }
        - name: jgroups.dns.query
          value: keycloak
        ports:
        - name: jgroups
          containerPort: 7600
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /health/ready
            port: 8443
          initialDelaySeconds: 120
          periodSeconds: 5

