apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mongo
  - ./opensearch
  #- HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

