apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: graylog-secret
  literals:
  - password=admin123