apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - HelmRelease.yaml
  - HelmRepository.yaml
  - namespace.yaml

patchesJson6902:
- target:
  - group: apps
    version: v1
    kind: Deployment
    name: powerdns-phpmyadmin
  - group: apps
    version: v1
    kind: Deployment
    name: powerdns-powerdns-admin
  - group: apps
    version: v1
    kind: StatefulSet
    name: powerdns-mariadb
  patch: |
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: amd5