apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keycloak-operator
  namespace: keycloak-operator
spec:
  interval: 5m
  url: https://nexus.systemtracker.no-ip.org/repository/keycloak/
  secretRef:
    name: keycloak-operator