apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-operator
  namespace: keycloak-operator
spec:
  encryptedData:
    password: AgAoBxQKGM5b38s7gZcRDJez3FUnOK5ea4FDdckIpBFHlFNWNSua5RroyFD4o30nPyTVm0egvrgvyh6Udzn5y2h3xjYI4ApNwGrdIcD5kibRfIU9FcAu/rMcMpIVmQep49WAE+ao+Zdw2XZaj7TbxCPPK9/HRvZ4BzQyBXuOkoutZf4V2jkTcyREEoUIaD/nC/Yh8RslQ+dVMGQbGOxKtmC3WnZShfMkAX41OayHdcJcPX7fMXTokIBTMz3dlymm/TFX3uY9K7Z4FGTS3YU+L8UPf9jci1c2oHKhuTY7DI1uUrcnKeuYMGMOj5DHVAsE7vdf09AKNvnU6VjeN2OCTV3rR7kX/5dFX5ATGk6Go0/Lq9c95+NM1Y6izdb3u338ksFCQChfekdWRAKmtHZjQTXZoaCZtXZUhTyP4mxvxam8wIyd97VqzM197fKBOdDeDx6rq31O3JAgygl+/qsFORLl25o8NHUfTg+uc0vmoVSGVqoJQPmzPkJCduZ4VlzlGVPhwmZipMbaxamghjE3Cn5OkP+cxL09qdGG3aFFKHfMgI6AtRlzjG+kujh2I2aZxxfk73zA7c9vpektjqXZatLVWtW9F5kSykSAEmRUKT9fP6HjFhemm6RvGGUYIAZ0wohiQpnxFNIYjXYrBhAQny+iR1E6Ss3m9cDWvOwTgegJR1hhwDJtlkq6lgLc11vexSrUpfNb
    username: AgABtvBbtHlWGXTdoi6mYsQMfsT/gqK+Ftf1PKmZHe7eapK/HDCp8vG8VO2nQNygxxH7+BMNi+0AAVWOS2dw4C54+NBiISlSJ/7mA8uoO1SqvWkQK8n5U9+idg82U852pPtiZvDo4WpQGLN4Cv4z5fEuIWMuQB2E8FIHCNXvOIwisUORAnFyil8yGUoqWVsStD99HkY+AtA+nWNt3bcjalpE9oBH3LjoNfudjoWvGXhzjlHbB/M8vr0Kk29Bpres195WBVgy1jGcaTIu4UuvxzX/qd4uwlolydy4ns0Dj0Ju873gOuKr8TuPhb3ohX2Eo5xGDQJ+cMu4HTJwJcrN+YPfnS5Ho/VEB/9I9QWHUMK2/9S20LTRiosYxAx/kNcr+6fBj3TWfVCyt6219Ri4ART3JpLwZNpf1cE5yBlvQJBJt7sx5K+F/2+MKOkfqSz//YtfatqOJw85G8CxlNWOgLi5cVkbWz065eBdGxhoFTeViPn87R3ghN9C/MgrWefFmN2ChGzFGxY0A/iyDE28P2vLua/cQGLR4+eO00kB2LsKTVJlnwZyaaM/JcBbnKP+Piyh3vwo+bzoXtHw8P3Rewgksb2k+dE/2IoYz0np2B3LQ+u4GRT3sE2eFok1kDXkKFq7W5EVTP/OF6VDOg25g04MyNdqaKQ6G04D0qKxEqOjnBmRQiLQNOPA0a/8HY0KcJ7XRKxN
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-operator
      namespace: keycloak-operator