apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: otc
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.21.5"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: otc
      interval: 5m
  values:
    monitoring:
      # -- Specifies whether the monitoring should be enabled. Requires Prometheus Operator CRDs.
      podMonitorEnabled: true
      grafanaDashboard:
        create: true